# Generated by Django 4.2.28 on 2026-03-01 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recommendations', '0001_initial'),
        ('textbooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='textbooks.category', verbose_name='分类'),
        ),
    ]
