# Generated by Django 4.2.28 on 2026-03-01 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recommendations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('textbooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='recommendationcache',
            name='textbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='textbooks.textbook', verbose_name='推荐教材'),
        ),
        migrations.AddField(
            model_name='recommendationcache',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_cache', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='browsinghistory',
            name='textbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browsing_records', to='textbooks.textbook', verbose_name='教材'),
        ),
        migrations.AddField(
            model_name='browsinghistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browsing_history', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterUniqueTogether(
            name='userpreference',
            unique_together={('user', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='recommendationcache',
            unique_together={('user', 'textbook')},
        ),
        migrations.AlterUniqueTogether(
            name='browsinghistory',
            unique_together={('user', 'textbook')},
        ),
    ]
