# Generated by Django 4.2.28 on 2026-03-17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('textbooks', '0003_textbookcomment_sharedresource_textbookvote'),
        ('recommendations', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='期望书名')),
                ('author', models.CharField(blank=True, default='', max_length=200, verbose_name='期望作者')),
                ('isbn', models.CharField(blank=True, default='', max_length=20, verbose_name='期望ISBN')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('priority', models.PositiveSmallIntegerField(default=3, verbose_name='优先级')),
                ('status', models.CharField(choices=[('open', '待满足'), ('matched', '已匹配'), ('closed', '已关闭')], default='open', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wishlist_items', to='textbooks.category', verbose_name='分类')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '心愿单',
                'verbose_name_plural': '心愿单',
                'db_table': 'wishlist_items',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
