# Generated by Django 4.2.28 on 2026-03-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(editable=False, max_length=32, unique=True, verbose_name='订单号')),
                ('transaction_type', models.CharField(max_length=10, verbose_name='交易类型')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='成交价格')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('completed', '已完成'), ('cancelled', '已取消'), ('returned', '已归还')], default='pending', max_length=10, verbose_name='订单状态')),
                ('rent_start_date', models.DateField(blank=True, null=True, verbose_name='租赁开始日期')),
                ('rent_end_date', models.DateField(blank=True, null=True, verbose_name='租赁结束日期')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
