# Generated by Django 4.2.28 on 2026-03-01 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('textbooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_orders', to=settings.AUTH_USER_MODEL, verbose_name='买方'),
        ),
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_orders', to=settings.AUTH_USER_MODEL, verbose_name='卖方'),
        ),
        migrations.AddField(
            model_name='order',
            name='textbook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='textbooks.textbook', verbose_name='教材'),
        ),
    ]
