# Generated by Django 4.2.28 on 2026-03-01 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('level', models.IntegerField(default=1, verbose_name='层级')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'db_table': 'categories',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='书名')),
                ('author', models.CharField(max_length=200, verbose_name='作者')),
                ('isbn', models.CharField(blank=True, default='', max_length=20, verbose_name='ISBN')),
                ('publisher', models.CharField(blank=True, default='', max_length=200, verbose_name='出版社')),
                ('edition', models.CharField(blank=True, default='', max_length=50, verbose_name='版本/版次')),
                ('condition', models.IntegerField(choices=[(5, '全新'), (4, '九成新'), (3, '七成新'), (2, '五成新'), (1, '较旧')], default=4, verbose_name='新旧程度')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='价格')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='原价')),
                ('transaction_type', models.CharField(choices=[('sell', '出售'), ('rent', '租赁'), ('free', '免费赠送')], default='sell', max_length=10, verbose_name='交易类型')),
                ('rent_duration', models.IntegerField(blank=True, null=True, verbose_name='租赁天数')),
                ('status', models.CharField(choices=[('pending_review', '待审核'), ('approved', '已通过'), ('rejected', '已驳回'), ('sold', '已售出'), ('rented', '已租出'), ('completed', '已完成'), ('offline', '已下架')], default='pending_review', max_length=20, verbose_name='状态')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='封面图')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='textbooks', to='textbooks.category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '教材',
                'verbose_name_plural': '教材',
                'db_table': 'textbooks',
                'ordering': ['-created_at'],
            },
        ),
    ]
