# Generated by Django 4.2.28 on 2026-03-04 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('textbooks', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextbookComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500, verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='textbooks.textbookcomment', verbose_name='父评论')),
                ('textbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='textbooks.textbook', verbose_name='教材')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='评论者')),
            ],
            options={
                'verbose_name': '教材评论',
                'verbose_name_plural': '教材评论',
                'db_table': 'textbook_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SharedResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('file', models.FileField(upload_to='resources/', verbose_name='文件')),
                ('file_size', models.IntegerField(default=0, verbose_name='文件大小(字节)')),
                ('resource_type', models.CharField(choices=[('pdf', 'PDF文档'), ('doc', 'Word文档'), ('ppt', 'PPT课件'), ('other', '其他')], default='pdf', max_length=10, verbose_name='类型')),
                ('download_count', models.IntegerField(default=0, verbose_name='下载次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='textbooks.category', verbose_name='分类')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '共享资料',
                'verbose_name_plural': '共享资料',
                'db_table': 'shared_resources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TextbookVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.SmallIntegerField(choices=[(1, '点赞'), (-1, '点踩')], verbose_name='投票')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('textbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='textbooks.textbook', verbose_name='教材')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '教材投票',
                'verbose_name_plural': '教材投票',
                'db_table': 'textbook_votes',
                'unique_together': {('textbook', 'user')},
            },
        ),
    ]
