# Generated by Django 4.2.28 on 2026-03-17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('textbooks', '0003_textbookcomment_sharedresource_textbookvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedresource',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='售价'),
        ),
        migrations.AddField(
            model_name='sharedresource',
            name='sale_type',
            field=models.CharField(choices=[('free', '免费'), ('sell', '售卖')], default='free', max_length=10, verbose_name='售卖类型'),
        ),
        migrations.CreateModel(
            name='ResourceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='成交价格')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '待支付'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=10, verbose_name='状态')),
                ('payment_qr', models.CharField(blank=True, default='', max_length=500, verbose_name='支付二维码链接')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_buy_orders', to=settings.AUTH_USER_MODEL, verbose_name='买家')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='textbooks.sharedresource', verbose_name='资料')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_sell_orders', to=settings.AUTH_USER_MODEL, verbose_name='卖家')),
            ],
            options={
                'verbose_name': '资料订单',
                'verbose_name_plural': '资料订单',
                'db_table': 'resource_orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
