# Generated by Django 4.2.28 on 2026-03-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbooks', '0004_sharedresource_sale_type_price_resourceorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceorder',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='支付时间'),
        ),
        migrations.AddField(
            model_name='resourceorder',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/', verbose_name='支付凭证'),
        ),
        migrations.AlterField(
            model_name='resourceorder',
            name='status',
            field=models.CharField(choices=[('pending', '待确认'), ('confirmed', '待支付'), ('paid_pending', '待卖家确认'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=10, verbose_name='状态'),
        ),
    ]
