# Generated by Django 4.2.28 on 2026-03-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbooks', '0005_resourceorder_payment_proof_paid_at_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceorder',
            name='status',
            field=models.CharField(choices=[('pending', '待确认'), ('confirmed', '待支付'), ('paid_pending', '待卖家确认'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
