# Generated by Django 4.2.28 on 2026-03-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', '通过'), ('rejected', '驳回')], max_length=10, verbose_name='审核结果')),
                ('reason', models.TextField(blank=True, default='', verbose_name='审核意见')),
                ('sensitive_words_found', models.TextField(blank=True, default='', verbose_name='命中敏感词')),
                ('is_auto', models.BooleanField(default=False, verbose_name='是否自动审核')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, verbose_name='审核时间')),
            ],
            options={
                'verbose_name': '审核记录',
                'verbose_name_plural': '审核记录',
                'db_table': 'review_records',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='SensitiveWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True, verbose_name='敏感词')),
                ('category', models.CharField(choices=[('political', '政治敏感'), ('violence', '暴力'), ('illegal', '违法'), ('other', '其他')], default='political', max_length=50, verbose_name='类别')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '敏感词',
                'verbose_name_plural': '敏感词',
                'db_table': 'sensitive_words',
            },
        ),
    ]
