# Generated by Django 4.2.28 on 2026-03-20 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(choices=[(1.0, '1分 - 差'), (1.5, '1.5分'), (2.0, '2分 - 一般'), (2.5, '2.5分'), (3.0, '3分 - 中等'), (3.5, '3.5分'), (4.0, '4分 - 很好'), (4.5, '4.5分'), (5.0, '5分 - 非常好')], decimal_places=1, max_digits=3, verbose_name='评分')),
                ('comment', models.CharField(blank=True, default='', max_length=200, verbose_name='评价内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('rater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_ratings', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '卖家评分',
                'verbose_name_plural': '卖家评分',
                'db_table': 'statistics_seller_ratings',
                'unique_together': {('seller', 'rater')},
            },
        ),
    ]
